### ISSUE TITLE
AKS labor

### ISSUE THREAD

**Issue by tothadam99** [bmeviaumb11/skalazhato#19]
Sziasztok!

Az AKS labor első feladatához szeretnék hozzászólni. Végigcsináltam a Microsoft féle mintaalkalmazás telepítését AKS-re. Az eredetileg beállított limitekkel nem működött, OOM hibát kaptam. A product konténernek több memória kellett.
A második feladatban találtam egy elgépelést. Frissítettem a traefik helmchartot, telepítettem, de a dashboard nem a 9000-es portot használja, hanem a 8080-at.

**Comment by tothadam99** [comment]
Hello!

A második feladatnál, mikor a db-ket kell kitenni, nem volt hajlandó az elastic mountolni a pv-t jogosultság hiányában. Ez a hiba a második labornál helyi K8s-en nem jelent meg, csak most AKS-en.
Az elastic replicaset template-jének a spec részét, az alábbiakkal egészítettem ki:

spec:
      securityContext:
        fsGroup: 1000
        
Valamint az elastic konténerhez felvettem egy újabb initContainer-t:
        - name: file-permissions
          image: busybox
          command: ['chown', '-R', '1000:1000', '/usr/share/elasticsearch/']
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-data
          securityContext:
            privileged: true
            runAsUser: 0
        
Ezek után már elindult a konténer, megjelentek info logok.

**Comment by kszicsillag** [comment]
Fixed as: https://github.com/bmeviaumb11/skalazhato/compare/48c140061f2867af27dc9562a63901c6b6108c6e..744b62f7f6a83592aff9a4fe22e6fc9e5ae91451
