### ISSUE TITLE
Megfogalmazás pontosítása a 2. laborban

### ISSUE THREAD

**Issue by WarHero21** [bmeviaumb11/skalazhato#8]
A 3.3. feladatban a 4. részben "src" helyett "src/Docker" van írva de nincsen ilyen könyvtár. A docker-compose a src mappában van simán.

**Comment by tibitoth** [comment]
Nyugodtan nyiss egy PR-t a javításról

**Comment by kszicsillag** [comment]
Fixed: https://github.com/bmeviaumb11/skalazhato/commit/2ef5614155e66c496b86e0773921b4d4044a74f2#diff-dafe8b54ac05a62e3a86a14d6a46ae3f8e2aefcdcd9173fcdca3b8607840af95L382
